# kubernetes/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: my-aro-app-service
spec:
  selector:
    app: my-aro-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
